### ISSUE TITLE
Google Fonts?

### ISSUE THREAD

**Issue by davelab6** [Isosceles/Pinnacle#4]
Great project! Would you be interested to see this available in Google Fonts?

If so, please file an "add font" issue in https://github.com/google/fonts/issues/new/choose :)

**Comment by lrenhrda** [comment]
Great idea! I've rearranged the repo to better match the guideilnes linked from add font form, and I've renamed it to be unique as well. Here's the link to the submission — https://github.com/google/fonts/issues/5630 🚀
